### ISSUE TITLE
Not working with external element display: table;

### ISSUE THREAD

**Issue by glaggia-larus** [kamilkp/angular-vs-repeat#149]
Hello, I have this piece of code:

```html
<div class="table" vs-repeat>
    <div ng-repeat="row in $ctrl.rows">
        <span>{{row.name}}</span>
    </div>
</div>
```

with class 'table':

```css
.table {
    display: table;
    height: 250px;
    overflow: auto;
}
```

This is breaking the behavior of vs-repeat rendering ALL the elements instead of only the current +2.

Is there any particular reason for this?
